using BraneCloud.Evolution.EC.GP;

namespace BraneCloud.Evolution.EC.App.Regression.Func
{
    /// <summary>
    /// Copyright 2012 by Sean Luke
    /// Licensed under the Academic Free License version 3.0
    /// See the file "LICENSE" for more information
    /// 
    /// VladERCB.java
    ///       
    /// Created: Wed Nov  3 18:26:37 1999
    /// By: Sean Luke
    /// 
    /// <p/>This ERC appears all three the Vladislavleva function sets.  It is not a constant but rather a function of one parameter (n) with an internal constant (c) and returns n + c. Note that the value of c is drawn from the fully-closed range [-5.0, 5.0].
    /// 
    /// <p/>E. Vladislavleva, G. Smits, and D. Den Hertog. Order of Nonlinearity as a Complexity Measure for Models Generated by Symbolic Regression via Pareto Genetic Programming. <i>IEEE Trans EC,</i> 13(2):333Ð349, 2009.
    /// </summary>
    public class VladERCB : VladERCA
    {
        public override string Name => "VladERCB";

        public override string ToStringForHumans()
        { return "n+" + (float)value; }

        public override void Eval(IEvolutionState state,
            int thread,
            GPData input,
            ADFStack stack,
            GPIndividual individual,
            IProblem problem)
        {
            var rd = (RegressionData)input;

            Children[0].Eval(state, thread, input, stack, individual, problem);
            rd.x = rd.x + value;
        }
    }
}


